version: 2.1

executors:
  executor:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/working_directory
    environment:
      TZ: "Asia/Tokyo"

jobs:
  build-image-and-push-to-ecr:
    executor: executor
    steps:
      - checkout
      - run:
          name: download go
          command: wget -O - "https://redirector.gvt1.com/edgedl/go/go1.9.2.linux-amd64.tar.gz" | tar zxvf - -C /home/circleci/working_directory
      - run:
          name: get ecr-helper
          command: ./go/bin/go get -u github.com/awslabs/amazon-ecr-credential-helper/ecr-login/cli/docker-credential-ecr-login
      - run:
          name: push to ecr
          command: |
            export PATH=$PATH:/home/circleci/go/bin/
            ./gradlew jib -Djib.to.tags=${CIRCLE_SHA1}

workflows:
  build-image-and-push-to-ecr:
    jobs:
      - build-image-and-push-to-ecr
